"""Init

Revision ID: 7fc850b29947
Revises: 
Create Date: 2023-04-01 22:31:02.900840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc850b29947'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('inn', sa.String(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('inn')
    )
    op.create_index(op.f('ix_participant_inn'), 'participant', ['inn'], unique=True)
    op.create_table('product',
    sa.Column('gtin', sa.String(), nullable=False),
    sa.Column('inn', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_short_name', sa.String(), nullable=False),
    sa.Column('tnved', sa.String(), nullable=False),
    sa.Column('tnved10', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['inn'], ['participant.inn'], ),
    sa.PrimaryKeyConstraint('gtin')
    )
    op.create_index(op.f('ix_product_gtin'), 'product', ['gtin'], unique=True)
    op.create_table('salespoint',
    sa.Column('id_sp', sa.String(), nullable=False),
    sa.Column('inn', sa.String(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('city_with_type', sa.String(), nullable=False),
    sa.Column('city_fias_id', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['inn'], ['participant.inn'], ),
    sa.PrimaryKeyConstraint('id_sp')
    )
    op.create_index(op.f('ix_salespoint_id_sp'), 'salespoint', ['id_sp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salespoint_id_sp'), table_name='salespoint')
    op.drop_table('salespoint')
    op.drop_index(op.f('ix_product_gtin'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_participant_inn'), table_name='participant')
    op.drop_table('participant')
    # ### end Alembic commands ###
